import { BLOCKCHAIN_NAMES, BlockchainName } from './blockchain-names';

export const BLOCKCHAIN_IDS: Record<BlockchainName, number> = {
    [BLOCKCHAIN_NAMES.ETHEREUM]: 1,
    [BLOCKCHAIN_NAMES.ARBITRUM]: 42161,
    [BLOCKCHAIN_NAMES.AVALANCHE]: 43114,
    [BLOCKCHAIN_NAMES.BNB]: 56,
    [BLOCKCHAIN_NAMES.LINEA]: 59144,
    [BLOCKCHAIN_NAMES.OPTIMISM]: 10,
    [BLOCKCHAIN_NAMES.POLYGON]: 137,
    [BLOCKCHAIN_NAMES.SCROLL]: 534352
} as const;
